apiVersion: v1
kind: ReplicationController
metadata:
  name: alpine-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: alpine-redis
    spec:
      containers:
        - name: alpine-redis
          image: registry.cn-shenzhen.aliyuncs.com/sjroom/alpine-redis
---
apiVersion: v1
kind: Service
metadata:
  name: alpine-redis
spec:
  type: NodePort
  ports:
    - port: 6379
      nodePort: 30006
  selector:
        name: alpine-redis
# https://raw.githubusercontent.com/zw23534572/alpine-redis/master/k8s.yaml